version: '2.4'

services:
  client:
    build:
      context: client
      args:
        GCV_SUB_URI: '${GCV_SUB_URI:-/}'
    ports:
      - "${GCV_PORT:-80}:80"
    depends_on:
      - server
    restart: always

  server:
    build: server
    environment:
      ALLOWED_HOSTS: '*'
      DEBUG: '0'
      GCV_SUB_URI: '/'
      PGDATABASE: postgres
      PGHOST: db
      PGNAME: postgres
      PGPASSWORD: "${POSTGRES_PASSWORD}"
      PGPORT: 5432
      PGUSER: postgres
    depends_on:
      db:
        condition: service_healthy
    restart: always
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "server.wsgi"]

  db:
    build: db
    environment:
      POSTGRES_PASSWORD:
    healthcheck:
      test: "pg_isready -U postgres -h 127.0.0.1 || exit 1"
      retries: 10
    restart: always
